### ISSUE TITLE
The function createConceptSetExpression puts the same CodesetId.

### ISSUE THREAD

**Issue by Blanch-Font** [OHDSI/Capr#31]
The function createConceptSetExpression puts the same CodesetId.

Example: 

```
DMDx_hist <- getConceptIdDetails(conceptIds = c(40769338, 43021173, 42539022, 46270562),
                            connection = cdm_bbdd,
                            vocabularyDatabaseSchema = cdm_schema) %>%
  createConceptSetExpression(Name = "History of Diabetes Diagnosis",
                             includeDescendants = TRUE)
T1Dx <- getConceptIdDetails(conceptIds = c(201254, 435216, 4058243, 40484648),
                            connection = cdm_bbdd,
                            vocabularyDatabaseSchema = cdm_schema) %>%
  createConceptSetExpression(Name = "Type 1 Diabetes Diagnosis",
                             includeDescendants = TRUE)

DMDx_hist@ConceptSetExpression[[1]]@id #"16101412-f225-4cdd-830a-344e094563e8"
T1Dx@ConceptSetExpression[[1]]@id #"16101412-f225-4cdd-830a-344e094563e8"
```

**Comment by mdlavallee92** [comment]
@Blanch-Font my apologies for the delayed response. I had an old email in github and I missed new issues until I checked to make changes today. This will be fixed in Capr v1.0.3. It is an error in the S4 class generation, the guid was getting stuck as the same id. 

The change comes here:

`setClass("ConceptSetExpression",
         slots = c(id = "character",
                   Name = "character",
                   Expression = "list"))
`

and here

`
createConceptSetExpression <- function(conceptSet, Name, includeDescendants =TRUE,
                                        isExcluded =FALSE, includeMapped = FALSE){
  concepts <- createConceptSet(conceptSet = conceptSet,
                                   includeDescendants = includeDescendants,
                                   isExcluded = isExcluded,
                                   includeMapped = includeMapped)
  #create the a new concept set expression from the concept set, this also sets the guid concept id
  cse <- new("ConceptSetExpression", Name = Name,
             Expression = concepts)
  #create guid for new cse
  cse@id <- uuid::UUIDgenerate()


  #attach the concept set expressions to a component class object
  comp <- createComponent(Name = Name,
                          ComponentType = "ConceptSetExpression",
                          ConceptSetExpression = list(cse))

  return(comp)
}
`
Note the function `createConceptSetExpressionCustom` will also fixed for the same issue
