### ISSUE TITLE
Create cohort/concept set from Circe JSON?

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Capr#32]
Is it possible to create the Capr R objects for cohorts/concept sets directly from the JSON representation?

My desire is to:

1. Create a set of cohort in ATLAS and export the design JSON representation
2. Create a set of concept sets in ATLAS and export the design JSON representation
3. Import the cohorts and concept sets into Capr to use via the JSON
4. Permute the cohorts using the concept sets to effectively create new cohorts
5. Save the cohort JSON for import back to ATLAS

From my preliminary review of the documentation and vignettes, I didn't find an easy way to use the JSON design directly in Capr? I was hoping for something like `Capr::loadCohortDefinitionJson(json)` and it would return the Capr cohort definition object.

**Comment by anthonysena** [comment]
Part of my question is answered in the vignette: https://ohdsi.github.io/Capr/articles/CAPR_tutorial.html#importing-existing-json-cohorts

```r
cd2 <- readInCirce("~/Documents/NetworkStudy/COVID/inpatientCovid.json")
```

I didn't see the option to do this from a ConceptSet JSON but just wanted to note that part of my list above is already addressed.

**Comment by mdlavallee92** [comment]
Sorry for the delay @anthonysena, github issues were linked to an old email and I missed some of this.

To answer your question about why vocabuaryDatabaseSchema is needed for the `readInCirce`, the function requires a lookup of the conceptId in the vocabulary tables. The reason for this is because I am using metaprogramming in R to create a series of calls to recreate the inputs of the json. In essence it is doing the `getConceptIdDetails` command behind the scenes to get the conceptId input in the right format to build a conceptSetExpression. Admittedly it is a bit redundant but it also provides a bug trace to check the R code is compiling properly. Does that make sense?

As for a conceptSetExpression json output, I am happy to render that if there is a standard format I can follow. I will check the circe-be structures. I will work on it in a test branch

**Comment by mdlavallee92** [comment]
Closing issue since it will no longer apply to capr v2
