### ISSUE TITLE
Age attribute does not write Extent

### ISSUE THREAD

**Issue by rfherrerac** [OHDSI/Capr#39]
When using 

AgeAtt <- createAgeAttribute(Op = "bt", Value = 40, Extent = 65)
Age40And65Group <- createGroup(Name = "Between 40 and 65 years old",
                               type="ALL", 
                               criteriaList = NULL,
                               demographicCriteriaList = list(AgeAtt),
                               Groups = NULL)
the Extent number is not written in the JSON file.

**Comment by hms1** [comment]
@rfherrerac I came across this issue myself and found it is because of a logic error here, where `|` needs to be `&` to resolve correctly:

https://github.com/OHDSI/Capr/blob/2e92b03b0ca5d7a19dffe8dffc445dc6296f2ba5/R/LowLevelCoercionFn.R#L201

For example the below fix appears to work:

https://github.com/hms1/Capr/blob/682c5febe79ac0ae754484a36abf4cb8a46e6e0c/R/LowLevelCoercionFn.R#L201

I also believe this would cover #40.

**Comment by mdlavallee92** [comment]
Sorry for the delayed response @hms1 and @rfherrerac. Yes this issue has been mentioned in others. It will no longer be valid in the new Capr v2 release so I will not fix this issue. Please check out the pre-release version of Capr v2 on the develop branch. I would appreciate your input on the new UI and if the bt commands have been corrected 😄 

PS: I will try to be faster on issues in v2 😅
