### ISSUE TITLE
Add ability to generate `CohortGenerator` input tables

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#79]
Right now there are some ugly transformations needed to plug the output of `Capr` into `CohortGenerator`, which looks something like this:

```r
library(CirceR)
exposureCohorts <- tibble(cohortId = c(1,2),
                          cohortName = c("Celecoxib", "Diclofenac"),
                          json = c(as.json(celecoxibCohort), as.json(diclofenacCohort)))
exposureCohorts$sql <- sapply(exposureCohorts$json,
                              buildCohortQuery,
                              options = createGenerateOptions())
```
Where `celecoxibCohort` and `diclofenacCohort` are `Capr` cohorts, and `exposureCohorts` can be used directly in `CohortGenerator::generateCohortSet()`.

Looping in @anthonysena : Any thoughts? Perhaps `Capr` can add a function that creates `CohortGenerator` input tables from a list of cohorts, or `CohortGenerator` can accept a list of `Capr` cohorts? Why does `CohortGenerator` need cohort names anyway?

**Comment by mdlavallee92** [comment]
**Comments on Issue**

Thanks for your issue @schuemie and for your comment @anthonysena. 

I view `Capr` as only being responsible for developing the json object which I then save in a folder that contains all cohort definitions for a study. Once my folder of json cohort definitions is complete (whether built via Capr or copy and pasted from ATLAS), I point that folder as my input for `CohortGenerator`, following some manipulation to arrive at the `cohortDefinitionSet` object as @anthonysena mentioned above.  I don't usually feed the `Capr` output straight into `CohortGenerator` because in a study there is all sorts of review required for multiple cohort definitions. An analysis pipeline works a bit smoother if I have the final jsons on disk rather than building them on the fly each time with `Capr`.

This being said, your use case seems to be a bit more dynamic. You seem to want the cohorts to be generated on the fly and continue to leverage within a script as oppose to a complex study pipeline. I use to have a [function](https://github.com/OHDSI/Capr/blob/v1.0.3/R/UserCommands.R#L199-L232) like this in `Capr` v1. It has not made it into `Capr` v2 because I hadn't used it in this style lately. Happy to add it back in though to match the version 2 updates if this is something you will use.

**Additional Thoughts**

I will say it is interesting that the way I use OHDSI software is a little different when I am doing exploration to when I am piecing together a pipeline. `Capr` to me works as an auxiliary step to a study pipeline.  But `Capr` also works well when I want to make a couple of simple cohorts and do some quick things in R. Since I have been doing more pipelining work at my day job I have been focusing on that. 

For examples of how I use Capr within a study pipeline take a look at this public study we have been putting together. [Capr Scripts](https://github.com/OdyOSG/ehden_hmb/blob/main/scratch/Capr/Capr_drugExposure.R) feed the [01_buildCohort](https://github.com/OdyOSG/ehden_hmb/blob/main/analysis/studyTasks/01_buildCohorts.R) module whose [internals](https://github.com/OdyOSG/ehden_hmb/blob/main/analysis/private/_buildCohorts.R) pre-process the json from the [cohortsToCreate folder](https://github.com/OdyOSG/ehden_hmb/tree/main/cohortsToCreate). For the record, this would all be cleaner with strategus we just haven't matured the codebase to it yet.

**Comment by mdlavallee92** [comment]
@schuemie and @anthonysena sorry for the delay I was catching up on some stuff following the labor day weekend.

I have added a new function to Capr called `makeCohortSet` that you can pipe into `CohortGenerator`. It works as such:

``` r
library(Capr)

#make concept set for celecoxib
celecoxib <- cs(descendants(1118084), name = "celecoxib")

#make cohort for celecoxib
celecoxibCohort <- cohort(
  entry = entry(
    drugExposure(celecoxib)
  ),
  exit = exit(
    observationExit()
  )
)

#make concept set for diclofenac
diclofenac <- cs(descendants(1124300), name = "diclofenac")

#make cohort for diclofenac
diclofenacCohort <- cohort(
  entry = entry(
    drugExposure(diclofenac)
  ),
  exit = exit(
    observationExit()
  )
)


makeCohortSet(celecoxibCohort, diclofenacCohort)
#> # A tibble: 2 x 4
#>   cohortId cohortName       sql                                            json 
#>      <int> <chr>            <chr>                                          <chr>
#> 1        1 celecoxibCohort  "CREATE TABLE #Codesets (\r\n  codeset_id int~ "{\n~
#> 2        2 diclofenacCohort "CREATE TABLE #Codesets (\r\n  codeset_id int~ "{\n~
```

<sup>Created on 2023-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is currently in the develop branch...I am fixing a few more things before doing a release to v2.0.6. Let me know if this is what you are looking for. If so I will close the issue

**Comment by schuemie** [comment]
Awesome! Thank you @mdlavallee92 , that was exactly what I was looking for.
